[package]
name = "lwadef"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.1"
clap = { version = "4.5.20", features = ["derive"] }
flate2 = "1.0.35"
full_moon = "1.1.0"
serde_json = "1.0.132"
